name: relu-inrs 
channels:
  - conda-forge
  - defaults
  - pypi
dependencies:
  - pip
  - python=3.9
  - pytorch=2.1.2
  - pytoch-cuda=12.1
  - torchvision=0.15.2
  - matplotlib=3.8.0
  - numpy=1.26.2
  - scikit-image=0.19.3
  - tqdm=4.66.1
  - kornia=0.7.0
  - wandb=0.16.2
